database:
  driverClass: org.h2.Driver
  # in-memory (named) H2 connection mode
  url: jdbc:h2:mem:test
  user: user_mngt_test
  password:
  properties:
    charSet: UTF-8
  validationQuery: "/* DB Health Check */ SELECT 1"
  # the max amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 3s
  validationQueryTimeout: 3s

flyway:
  locations:
    - db/migration

swagger:
  resourcePackage: com.crm.umt.controller
  title: User Management Service

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081