CREATE TABLE USER
(
    ID INTEGER auto_increment,
    E_MAIL CHARACTER(150) NOT NULL,
    FIRST_NAME CHARACTER(100) NOT NULL,
    LAST_NAME CHARACTER(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    DELETED_AT TIMESTAMP,
    PRIMARY KEY (ID)
);