INSERT INTO USER (E_MAIL, FIRST_NAME, LAST_NAME, CREATED_AT, DELETED_AT)
VALUES ('adfs@gmail.com', 'Hello', 'World', CURRENT_TIMESTAMP, NULL);

INSERT INTO USER (E_MAIL, FIRST_NAME, LAST_NAME, CREATED_AT, DELETED_AT)
VALUES ('adfs2@gmail.com', 'Hello2', 'World2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO USER (E_MAIL, FIRST_NAME, LAST_NAME, CREATED_AT, DELETED_AT)
VALUES ('adfs3@gmail.com', 'Hello3', 'World3', CURRENT_TIMESTAMP, NULL);